# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainFrame.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QStatusBar, QTableWidget, QTableWidgetItem, QTextEdit,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1090, 793)
        MainWindow.setMinimumSize(QSize(200, 167))
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(200, 167))
        self.mainBgWidget = QWidget(self.centralwidget)
        self.mainBgWidget.setObjectName(u"mainBgWidget")
        self.mainBgWidget.setGeometry(QRect(9, 9, 1072, 753))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 127, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(255, 63, 63, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(127, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(170, 0, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        brush7 = QBrush(QColor(30, 31, 34, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.mainBgWidget.setPalette(palette)
        self.mainBgWidget.setAutoFillBackground(True)
        self.line = QFrame(self.mainBgWidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-20, 100, 1101, 16))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.line.setPalette(palette1)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.widgetTopMenu_3 = QWidget(self.mainBgWidget)
        self.widgetTopMenu_3.setObjectName(u"widgetTopMenu_3")
        self.widgetTopMenu_3.setGeometry(QRect(0, 0, 1071, 111))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Base, brush6)
        brush9 = QBrush(QColor(43, 45, 48, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.widgetTopMenu_3.setPalette(palette2)
        self.widgetTopMenu_3.setAutoFillBackground(True)
        self.btCampo = QPushButton(self.widgetTopMenu_3)
        self.btCampo.setObjectName(u"btCampo")
        self.btCampo.setGeometry(QRect(370, 20, 151, 71))
        self.btRegistro = QPushButton(self.widgetTopMenu_3)
        self.btRegistro.setObjectName(u"btRegistro")
        self.btRegistro.setGeometry(QRect(530, 20, 151, 71))
        self.btIndices = QPushButton(self.widgetTopMenu_3)
        self.btIndices.setObjectName(u"btIndices")
        self.btIndices.setGeometry(QRect(690, 20, 141, 71))
        self.btEstandarizacion = QPushButton(self.widgetTopMenu_3)
        self.btEstandarizacion.setObjectName(u"btEstandarizacion")
        self.btEstandarizacion.setGeometry(QRect(840, 20, 141, 71))
        self.btArchivo = QPushButton(self.widgetTopMenu_3)
        self.btArchivo.setObjectName(u"btArchivo")
        self.btArchivo.setGeometry(QRect(210, 20, 151, 71))
        self.stackedMenus = QStackedWidget(self.mainBgWidget)
        self.stackedMenus.setObjectName(u"stackedMenus")
        self.stackedMenus.setGeometry(QRect(0, 90, 211, 661))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setAutoFillBackground(True)
        self.layoutArchivo = QWidget(self.page)
        self.layoutArchivo.setObjectName(u"layoutArchivo")
        self.layoutArchivo.setGeometry(QRect(0, -10, 211, 671))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.layoutArchivo.setPalette(palette3)
        self.layoutArchivo.setAutoFillBackground(True)
        self.wd_archivo4 = QWidget(self.layoutArchivo)
        self.wd_archivo4.setObjectName(u"wd_archivo4")
        self.wd_archivo4.setGeometry(QRect(10, 290, 181, 31))
        palette4 = QPalette()
        brush10 = QBrush(QColor(113, 118, 126, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wd_archivo4.setPalette(palette4)
        self.wd_archivo4.setAutoFillBackground(True)
        self.lb_archivo4 = QLabel(self.wd_archivo4)
        self.lb_archivo4.setObjectName(u"lb_archivo4")
        self.lb_archivo4.setGeometry(QRect(0, 0, 181, 31))
        self.lb_archivo4.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_archivo4.setAlignment(Qt.AlignCenter)
        self.wdArchivo1 = QWidget(self.layoutArchivo)
        self.wdArchivo1.setObjectName(u"wdArchivo1")
        self.wdArchivo1.setGeometry(QRect(10, 50, 181, 31))
        palette5 = QPalette()
        brush11 = QBrush(QColor(100, 105, 112, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdArchivo1.setPalette(palette5)
        self.wdArchivo1.setAutoFillBackground(True)
        self.lb_archivo1 = QLabel(self.wdArchivo1)
        self.lb_archivo1.setObjectName(u"lb_archivo1")
        self.lb_archivo1.setEnabled(True)
        self.lb_archivo1.setGeometry(QRect(0, 0, 181, 31))
        self.lb_archivo1.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_archivo1.setAlignment(Qt.AlignCenter)
        self.wdArchivo2 = QWidget(self.layoutArchivo)
        self.wdArchivo2.setObjectName(u"wdArchivo2")
        self.wdArchivo2.setGeometry(QRect(10, 130, 181, 31))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdArchivo2.setPalette(palette6)
        self.wdArchivo2.setAutoFillBackground(True)
        self.lb_archivo2 = QLabel(self.wdArchivo2)
        self.lb_archivo2.setObjectName(u"lb_archivo2")
        self.lb_archivo2.setGeometry(QRect(0, 0, 181, 31))
        self.lb_archivo2.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_archivo2.setAlignment(Qt.AlignCenter)
        self.wdArchivo3 = QWidget(self.layoutArchivo)
        self.wdArchivo3.setObjectName(u"wdArchivo3")
        self.wdArchivo3.setGeometry(QRect(10, 210, 181, 31))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdArchivo3.setPalette(palette7)
        self.wdArchivo3.setAutoFillBackground(True)
        self.lb_archivo3 = QLabel(self.wdArchivo3)
        self.lb_archivo3.setObjectName(u"lb_archivo3")
        self.lb_archivo3.setGeometry(QRect(0, 0, 181, 31))
        self.lb_archivo3.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_archivo3.setAlignment(Qt.AlignCenter)
        self.wd_archivo5 = QWidget(self.layoutArchivo)
        self.wd_archivo5.setObjectName(u"wd_archivo5")
        self.wd_archivo5.setGeometry(QRect(10, 370, 181, 31))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wd_archivo5.setPalette(palette8)
        self.wd_archivo5.setAutoFillBackground(True)
        self.lb_archivo5 = QLabel(self.wd_archivo5)
        self.lb_archivo5.setObjectName(u"lb_archivo5")
        self.lb_archivo5.setGeometry(QRect(0, 0, 181, 31))
        self.lb_archivo5.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_archivo5.setAlignment(Qt.AlignCenter)
        self.wdArchivo1.raise_()
        self.wdArchivo2.raise_()
        self.wdArchivo3.raise_()
        self.wd_archivo4.raise_()
        self.wd_archivo5.raise_()
        self.stackedMenus.addWidget(self.page)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setAutoFillBackground(True)
        self.layoutRegistro = QWidget(self.page_3)
        self.layoutRegistro.setObjectName(u"layoutRegistro")
        self.layoutRegistro.setGeometry(QRect(0, -10, 211, 671))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.layoutRegistro.setPalette(palette9)
        self.layoutRegistro.setAutoFillBackground(True)
        self.wdRegistros4 = QWidget(self.layoutRegistro)
        self.wdRegistros4.setObjectName(u"wdRegistros4")
        self.wdRegistros4.setGeometry(QRect(10, 290, 181, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wdRegistros4.setPalette(palette10)
        self.wdRegistros4.setAutoFillBackground(True)
        self.lb_registros4 = QLabel(self.wdRegistros4)
        self.lb_registros4.setObjectName(u"lb_registros4")
        self.lb_registros4.setGeometry(QRect(0, 0, 181, 31))
        self.lb_registros4.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_registros4.setAlignment(Qt.AlignCenter)
        self.wdRegistros1 = QWidget(self.layoutRegistro)
        self.wdRegistros1.setObjectName(u"wdRegistros1")
        self.wdRegistros1.setGeometry(QRect(10, 50, 181, 31))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdRegistros1.setPalette(palette11)
        self.wdRegistros1.setAutoFillBackground(True)
        self.lb_registros1 = QLabel(self.wdRegistros1)
        self.lb_registros1.setObjectName(u"lb_registros1")
        self.lb_registros1.setEnabled(True)
        self.lb_registros1.setGeometry(QRect(0, 0, 181, 31))
        self.lb_registros1.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_registros1.setAlignment(Qt.AlignCenter)
        self.wdRegistros2 = QWidget(self.layoutRegistro)
        self.wdRegistros2.setObjectName(u"wdRegistros2")
        self.wdRegistros2.setGeometry(QRect(10, 130, 181, 31))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdRegistros2.setPalette(palette12)
        self.wdRegistros2.setAutoFillBackground(True)
        self.lb_registros2 = QLabel(self.wdRegistros2)
        self.lb_registros2.setObjectName(u"lb_registros2")
        self.lb_registros2.setGeometry(QRect(0, 0, 181, 31))
        self.lb_registros2.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_registros2.setAlignment(Qt.AlignCenter)
        self.wdRegistros3 = QWidget(self.layoutRegistro)
        self.wdRegistros3.setObjectName(u"wdRegistros3")
        self.wdRegistros3.setGeometry(QRect(10, 210, 181, 31))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdRegistros3.setPalette(palette13)
        self.wdRegistros3.setAutoFillBackground(True)
        self.lb_registros3 = QLabel(self.wdRegistros3)
        self.lb_registros3.setObjectName(u"lb_registros3")
        self.lb_registros3.setGeometry(QRect(0, 0, 181, 31))
        self.lb_registros3.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_registros3.setAlignment(Qt.AlignCenter)
        self.wdRegistros5 = QWidget(self.layoutRegistro)
        self.wdRegistros5.setObjectName(u"wdRegistros5")
        self.wdRegistros5.setGeometry(QRect(10, 370, 181, 31))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wdRegistros5.setPalette(palette14)
        self.wdRegistros5.setAutoFillBackground(True)
        self.lb_registros5 = QLabel(self.wdRegistros5)
        self.lb_registros5.setObjectName(u"lb_registros5")
        self.lb_registros5.setGeometry(QRect(0, 0, 181, 31))
        self.lb_registros5.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_registros5.setAlignment(Qt.AlignCenter)
        self.stackedMenus.addWidget(self.page_3)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.page_5.setAutoFillBackground(True)
        self.layoutEstandar = QWidget(self.page_5)
        self.layoutEstandar.setObjectName(u"layoutEstandar")
        self.layoutEstandar.setGeometry(QRect(0, 0, 211, 671))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.layoutEstandar.setPalette(palette15)
        self.layoutEstandar.setAutoFillBackground(True)
        self.wdEstandar2 = QWidget(self.layoutEstandar)
        self.wdEstandar2.setObjectName(u"wdEstandar2")
        self.wdEstandar2.setGeometry(QRect(10, 290, 181, 31))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wdEstandar2.setPalette(palette16)
        self.wdEstandar2.setAutoFillBackground(True)
        self.lb_estandar2 = QLabel(self.wdEstandar2)
        self.lb_estandar2.setObjectName(u"lb_estandar2")
        self.lb_estandar2.setGeometry(QRect(0, 0, 181, 31))
        self.lb_estandar2.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_estandar2.setAlignment(Qt.AlignCenter)
        self.wdEstandar1 = QWidget(self.layoutEstandar)
        self.wdEstandar1.setObjectName(u"wdEstandar1")
        self.wdEstandar1.setGeometry(QRect(10, 130, 181, 31))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdEstandar1.setPalette(palette17)
        self.wdEstandar1.setAutoFillBackground(True)
        self.lb_estandar1 = QLabel(self.wdEstandar1)
        self.lb_estandar1.setObjectName(u"lb_estandar1")
        self.lb_estandar1.setGeometry(QRect(0, 0, 181, 31))
        self.lb_estandar1.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_estandar1.setAlignment(Qt.AlignCenter)
        self.stackedMenus.addWidget(self.page_5)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setAutoFillBackground(True)
        self.layoutCampos_2 = QWidget(self.page_4)
        self.layoutCampos_2.setObjectName(u"layoutCampos_2")
        self.layoutCampos_2.setGeometry(QRect(0, 0, 211, 671))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.layoutCampos_2.setPalette(palette18)
        self.layoutCampos_2.setAutoFillBackground(True)
        self.wdIndices2 = QWidget(self.layoutCampos_2)
        self.wdIndices2.setObjectName(u"wdIndices2")
        self.wdIndices2.setGeometry(QRect(10, 290, 181, 31))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wdIndices2.setPalette(palette19)
        self.wdIndices2.setAutoFillBackground(True)
        self.lb_indices2 = QLabel(self.wdIndices2)
        self.lb_indices2.setObjectName(u"lb_indices2")
        self.lb_indices2.setGeometry(QRect(0, 0, 181, 31))
        self.lb_indices2.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_indices2.setAlignment(Qt.AlignCenter)
        self.wdIndices1 = QWidget(self.layoutCampos_2)
        self.wdIndices1.setObjectName(u"wdIndices1")
        self.wdIndices1.setGeometry(QRect(10, 130, 181, 31))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdIndices1.setPalette(palette20)
        self.wdIndices1.setAutoFillBackground(True)
        self.lb_indices1 = QLabel(self.wdIndices1)
        self.lb_indices1.setObjectName(u"lb_indices1")
        self.lb_indices1.setGeometry(QRect(0, 0, 181, 31))
        self.lb_indices1.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_indices1.setAlignment(Qt.AlignCenter)
        self.stackedMenus.addWidget(self.page_4)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setAutoFillBackground(True)
        self.layoutCampos = QWidget(self.page_2)
        self.layoutCampos.setObjectName(u"layoutCampos")
        self.layoutCampos.setGeometry(QRect(0, 0, 211, 671))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette21.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.layoutCampos.setPalette(palette21)
        self.layoutCampos.setAutoFillBackground(True)
        self.wdCampos4 = QWidget(self.layoutCampos)
        self.wdCampos4.setObjectName(u"wdCampos4")
        self.wdCampos4.setGeometry(QRect(10, 290, 181, 31))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette22.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette22.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette22.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.wdCampos4.setPalette(palette22)
        self.wdCampos4.setAutoFillBackground(True)
        self.lb_campos4 = QLabel(self.wdCampos4)
        self.lb_campos4.setObjectName(u"lb_campos4")
        self.lb_campos4.setGeometry(QRect(0, 0, 181, 31))
        self.lb_campos4.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_campos4.setAlignment(Qt.AlignCenter)
        self.wdCampos1 = QWidget(self.layoutCampos)
        self.wdCampos1.setObjectName(u"wdCampos1")
        self.wdCampos1.setGeometry(QRect(10, 50, 181, 31))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdCampos1.setPalette(palette23)
        self.wdCampos1.setAutoFillBackground(True)
        self.lb_Campos1 = QLabel(self.wdCampos1)
        self.lb_Campos1.setObjectName(u"lb_Campos1")
        self.lb_Campos1.setEnabled(True)
        self.lb_Campos1.setGeometry(QRect(0, 0, 181, 31))
        self.lb_Campos1.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_Campos1.setAlignment(Qt.AlignCenter)
        self.wdCampos2 = QWidget(self.layoutCampos)
        self.wdCampos2.setObjectName(u"wdCampos2")
        self.wdCampos2.setGeometry(QRect(10, 130, 181, 31))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdCampos2.setPalette(palette24)
        self.wdCampos2.setAutoFillBackground(True)
        self.lb_Campos2 = QLabel(self.wdCampos2)
        self.lb_Campos2.setObjectName(u"lb_Campos2")
        self.lb_Campos2.setGeometry(QRect(0, 0, 181, 31))
        self.lb_Campos2.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_Campos2.setAlignment(Qt.AlignCenter)
        self.wdCampos3 = QWidget(self.layoutCampos)
        self.wdCampos3.setObjectName(u"wdCampos3")
        self.wdCampos3.setGeometry(QRect(10, 210, 181, 31))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.wdCampos3.setPalette(palette25)
        self.wdCampos3.setAutoFillBackground(True)
        self.lb_campos3 = QLabel(self.wdCampos3)
        self.lb_campos3.setObjectName(u"lb_campos3")
        self.lb_campos3.setGeometry(QRect(0, 0, 181, 31))
        self.lb_campos3.setCursor(QCursor(Qt.PointingHandCursor))
        self.lb_campos3.setAlignment(Qt.AlignCenter)
        self.stackedMenus.addWidget(self.page_2)
        self.stackedPanels = QStackedWidget(self.mainBgWidget)
        self.stackedPanels.setObjectName(u"stackedPanels")
        self.stackedPanels.setGeometry(QRect(210, 90, 861, 661))
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.page1.setAutoFillBackground(True)
        self.widgetCrearArchivo = QWidget(self.page1)
        self.widgetCrearArchivo.setObjectName(u"widgetCrearArchivo")
        self.widgetCrearArchivo.setGeometry(QRect(0, 0, 861, 661))
        self.widgetCrearArchivo.setAutoFillBackground(True)
        self.tableWidget = QTableWidget(self.widgetCrearArchivo)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(100, 90, 661, 361))
        self.txtFileName = QTextEdit(self.widgetCrearArchivo)
        self.txtFileName.setObjectName(u"txtFileName")
        self.txtFileName.setGeometry(QRect(380, 50, 261, 31))
        self.labelFileName = QLabel(self.widgetCrearArchivo)
        self.labelFileName.setObjectName(u"labelFileName")
        self.labelFileName.setGeometry(QRect(210, 60, 161, 20))
        palette26 = QPalette()
        brush12 = QBrush(QColor(236, 236, 236, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush12)
        palette26.setBrush(QPalette.Active, QPalette.Button, brush6)
        palette26.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette26.setBrush(QPalette.Active, QPalette.Midlight, brush6)
        brush13 = QBrush(QColor(127, 127, 127, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette26.setBrush(QPalette.Active, QPalette.Dark, brush13)
        brush14 = QBrush(QColor(170, 170, 170, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette26.setBrush(QPalette.Active, QPalette.Mid, brush14)
        palette26.setBrush(QPalette.Active, QPalette.Text, brush)
        palette26.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette26.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette26.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette26.setBrush(QPalette.Active, QPalette.Window, brush6)
        palette26.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette26.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        palette26.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette26.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush15 = QBrush(QColor(0, 0, 0, 127))
        brush15.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette26.setBrush(QPalette.Active, QPalette.PlaceholderText, brush15)
#endif
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        palette26.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.Dark, brush13)
        palette26.setBrush(QPalette.Inactive, QPalette.Mid, brush14)
        palette26.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.Window, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette26.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette26.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette26.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
#endif
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        palette26.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.Midlight, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.Dark, brush13)
        palette26.setBrush(QPalette.Disabled, QPalette.Mid, brush14)
        palette26.setBrush(QPalette.Disabled, QPalette.Text, brush13)
        palette26.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.ButtonText, brush13)
        palette26.setBrush(QPalette.Disabled, QPalette.Base, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.Window, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush6)
        palette26.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette26.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush16 = QBrush(QColor(127, 127, 127, 127))
        brush16.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette26.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
#endif
        self.labelFileName.setPalette(palette26)
        self.stackedPanels.addWidget(self.page1)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.stackedPanels.addWidget(self.page_7)
        self.line.raise_()
        self.stackedPanels.raise_()
        self.stackedMenus.raise_()
        self.widgetTopMenu_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedMenus.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btCampo.setText(QCoreApplication.translate("MainWindow", u"Campo", None))
        self.btRegistro.setText(QCoreApplication.translate("MainWindow", u"Registro", None))
        self.btIndices.setText(QCoreApplication.translate("MainWindow", u"Indices", None))
        self.btEstandarizacion.setText(QCoreApplication.translate("MainWindow", u"Estandarizacion", None))
        self.btArchivo.setText(QCoreApplication.translate("MainWindow", u"Archivo", None))
        self.lb_archivo4.setText(QCoreApplication.translate("MainWindow", u"Cerrar Archivo", None))
        self.lb_archivo1.setText(QCoreApplication.translate("MainWindow", u"Nuevo Archivo", None))
        self.lb_archivo2.setText(QCoreApplication.translate("MainWindow", u"Abrir Archivo", None))
        self.lb_archivo3.setText(QCoreApplication.translate("MainWindow", u"Salvar Archivo", None))
        self.lb_archivo5.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.lb_registros4.setText(QCoreApplication.translate("MainWindow", u"Borrar Registros", None))
        self.lb_registros1.setText(QCoreApplication.translate("MainWindow", u"Introducir Registros", None))
        self.lb_registros2.setText(QCoreApplication.translate("MainWindow", u"Modificar Registros", None))
        self.lb_registros3.setText(QCoreApplication.translate("MainWindow", u"Buscar Registros", None))
        self.lb_registros5.setText(QCoreApplication.translate("MainWindow", u"Listar Registros", None))
        self.lb_estandar2.setText(QCoreApplication.translate("MainWindow", u"Exportar XML con Schema", None))
        self.lb_estandar1.setText(QCoreApplication.translate("MainWindow", u"Exportar Excel", None))
        self.lb_indices2.setText(QCoreApplication.translate("MainWindow", u"Re Indexar Archivos", None))
        self.lb_indices1.setText(QCoreApplication.translate("MainWindow", u"Crear \u00cdndices", None))
        self.lb_campos4.setText(QCoreApplication.translate("MainWindow", u"Borrar Campos", None))
        self.lb_Campos1.setText(QCoreApplication.translate("MainWindow", u"Crear Campos", None))
        self.lb_Campos2.setText(QCoreApplication.translate("MainWindow", u"Listar Campos", None))
        self.lb_campos3.setText(QCoreApplication.translate("MainWindow", u"Modificar Campos", None))
        self.labelFileName.setText(QCoreApplication.translate("MainWindow", u"Ingrese Nombre de Archivo:", None))
    # retranslateUi

